import Head from 'next/head';
import LinkList from '../components/LinkList.component';
import Nav from '../components/Nav.component';
import Search from '../components/Search.component';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section className='center w85'>
				<Nav />

				<div className='ph3 pv1 background-gray'>
					<LinkList />
				</div>
			</section>
			<Search />
		</>
	);
}
